name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup
      run: |
        sudo apt install pylint3
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        python3 -m pylint --version
        echo test, and deploy your project.
